project_name: consulssm
release:
  github:
    owner: bdclark
    name: consulssm
  name_template: '{{ .Tag }}'
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X github.com/bdclark/consulssm/version.Version={{ .Version }} -X github.com/bdclark/consulssm/version.GitCommit={{ .Commit }}
  binary: consulssm
brew:
  github:
    owner: bdclark
    name: homebrew-tap
  commit_author:
    name: bdclark
    email: brian@clark.zone
  folder: Formula
  homepage: https://github.com/bdclark/consulssm
  install: bin.install "consulssm"
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
