
[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.7"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.13.41"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"
